version: '3'
networks:
  default:
    external:
      name: ccp-network
services:
  ccp_back:
    container_name: ccp_back
    build: ./ccp_back
    restart: always
    ports:
      - "6001:4000"
    networks:
      default:
        aliases:
          - ccp_back.ccp-network
    depends_on:
      - ccp_db
    links:
      - ccp_db


  ccp_db:
    container_name: ccp_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: pg1313LK3fpjlk
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '6002:5432'
    networks:
      default:
        aliases:
          - ccp_db.ccp-network

  ccp_ui:
    container_name: ccp_ui
    build: ./ccp_ui
    restart: always
    ports:
      - "6500:3000"
    networks:
      default:
        aliases:
          - ccp_ui.ccp-network
    depends_on:
      - ccp_back
    links:
      - ccp_back
